### ISSUE TITLE
disabling blinking emissive texture

### ISSUE THREAD

**Issue by Kaanta0** [SJKZ1-2565/EmissiveSkinRenderer#1]
hoow can i disable the animation ? i want the emission to always be on.

**Comment by SJKZ1-2565** [comment]
It can't but it's such a good idea to add it

**Comment by Kaanta0** [comment]
i have a Dr.Manhattan skin and wanted to have the same glow that he has lol

**Comment by SJKZ1-2565** [comment]
Show me some example?

**Comment by SJKZ1-2565** [comment]
Nvm I see
