### ISSUE TITLE
skin editor menu doesnt open (2.10 and older) 

### ISSUE THREAD

**Issue by Blisterexe** [SJKZ1-2565/EmissiveSkinRenderer#2]
it doesnt work on the betteradventures+ modpack.

**Comment by Blisterexe** [comment]
or the other ones ive tried for that matter

**Comment by SJKZ1-2565** [comment]
Unfortunately that version is not support anymore I will not work on that again

**Comment by Blisterexe** [comment]
apologies, i did not notice
